version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - json-server

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - "3004:3004"
    volumes:
      - ./src/assets/db.json:/data/db.json
